//Dead or Wounded game

import java.util.Scanner;
import java.util.Random;

public class DeadOrWounded {
	public static void main(String[] args) {
	    //Create welcome message 
		System.out.println("===============================\n     Dead or Wounded game     \n===============================");
		System.out.println("Welcome to Dead or Wounded.");
		System.out.println("Guess the secret 4-digit number in the fewest possible attempts. \nGoodluck!");
		System.out.println("===============================");
		
		//Receive input to either start or exit the game.
		Scanner input1 = new Scanner(System.in);
		System.out.println("Enter 1 to start or 0 to exit: ");
		int begin = input1.nextInt();
        
        //This code runs if the user enters 1, indicating the start of the game.
        if (begin == 1) {
		    
		    //Secret number is generated by using the random function
		    Random randomObject = new Random(); 
		    
		    int attempts = 0;
		    int dead = 0;
		    int wounded = 0;
		    
		    String secretNumber = "";
		    
		    int firstDigit = randomObject.nextInt(9) + 1;
		    secretNumber += firstDigit;
		    
		    while (secretNumber.length() < 4) {
		        int remainingDigits = randomObject.nextInt(10);
		        
		        if (!secretNumber.contains(String.valueOf(remainingDigits))) {
		            secretNumber += remainingDigits;
		        }
		                 
		    }
		    
		    
		    //Validate if user's guess is valid
		    while (dead != 4) {
		        dead = 0;
		        wounded = 0;
		        
		        boolean allDigits = true;
		        boolean duplicate  = false;
		        
		        
		        System.out.println("Enter your guess: ");
		        String guess = input1.next();
		        
		        if (guess.length() != 4) {
		            System.out.println("Invalid input. Please enter a 4-digit number.");
		        }
		        else {
		            for (int i = 0; i < guess.length(); i++) {
		                if (!Character.isDigit(guess.charAt(i))) {
		                   allDigits = false;
		                }
		            }
		        if (!allDigits) {
		                System.out.println("Invalid input. Please enter only numbers.");
		            
		        } else {
		                for (int j = 0; j < guess.length(); j++) {
		                    for (int k = j + 1; k < guess.length(); k++) {
		                        if (guess.charAt(j) == guess.charAt(k)) {
		                            duplicate = true;
		                            break;
		                        }
		                    }
		                }
		                if (duplicate) {
		                    System.out.println("Invalid input. Please enter 4 unique digits.");
		                }
		                else {
		                    attempts++; //Count the number of attemps it takes to guess the secret number
		                    for (int i = 0; i < guess.length(); i++) {
		                        if (guess.charAt(i) == secretNumber.charAt(i)) {
		                           dead++; //Calculate dead values
		                        }
		                    }
		                    
		                    for (int i = 0; i < guess.length(); i++) {
		                        for (int j = 0; j < secretNumber.length(); j++) {
		                            if (guess.charAt(i) == secretNumber.charAt(j) && i != j) {
		                                wounded++; //Calculate wounded values
		                            }
		                        }
		                    }
		                    //Display dead and wounded values
		                    System.out.println("Dead: " + dead);
		                    System.out.println("Wounded: " + wounded);
		                }
		              }
		           }
		      }
		      //Display congratulatory message and number of attempts
		      System.out.println("Congratulations! You have guessed correctly.");
		      System.out.println("Number of attempts: " + attempts);
	    }
	    //This code is printed the player does not want to play
        else if (begin == 0) {
		    System.out.println("Thank you for playing.");
        }
        //Ensures that only valid input kf 1 or 0 is accepted to start the game.
        else {
		    System.out.println("Please enter a valid number. 1 to start and 0 to exit.");
		}
		
	  }
	  
} 
